---
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  ImagemagickLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: ImageMagickLayer
      Description: Imagemagick 7
      ContentUri: "./build/layer.zip"
      CompatibleRuntimes:
        - provided.al2
        - python3.8
        - nodejs10.x
        - nodejs12.x
        - ruby2.7
      RetentionPolicy: Retain
Outputs:
  ImagemagickLayerOutput:
    Description: ImageMagick Layer Version
    Value: !Ref ImagemagickLayer
